-- public.courses definition

-- Drop table

-- DROP TABLE public.courses;

CREATE TABLE public.courses (
	course_code varchar(20) NOT NULL,
	course_name varchar(255) NULL,
	course_description text NULL,
	date_created timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	date_modified timestamp NULL,
	modified_by numeric(19, 2) NULL,
	status varchar(255) NULL,
	education_level varchar(255) NULL,
	course_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	CONSTRAINT programs_pkey PRIMARY KEY (course_code)
);

-- public.staff definition

-- Drop table

-- DROP TABLE public.staff;

CREATE TABLE public.staff (
	user_types_id numeric(19, 2) NULL,
	usr_auth_salt varchar(255) NULL,
	usr_created_by numeric(19, 2) NULL,
	usr_date_created timestamp NULL,
	usr_date_modified timestamp NULL,
	usr_email varchar(255) NULL,
	usr_full_name varchar(255) NULL,
	usr_last_login timestamp NULL,
	usr_modified_by numeric(19, 2) NULL,
	usr_roles varchar(255) NULL,
	usr_session_expiry timestamp NULL,
	usr_staff_id varchar(255) NOT NULL,
	usr_status varchar(255) NULL,
	usr_username varchar(255) NOT NULL,
	usr_title varchar(255) NULL,
	usr_education_level varchar(255) NULL,
	usr_id int8 NOT NULL GENERATED ALWAYS AS IDENTITY,
	usr_phone_no varchar(15) NULL,
	CONSTRAINT staff_pk PRIMARY KEY (usr_id),
	CONSTRAINT staff_un UNIQUE (usr_staff_id)
);

-- public.activities definition

-- Drop table

-- DROP TABLE public.activities;

CREATE TABLE public.activities (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	activity_name varchar(200) NULL,
	description text NULL,
	activity_date date NULL,
	status varchar(10) NULL,
	created_on timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT activities_pk PRIMARY KEY (id)
);


-- public.communications definition

-- Drop table

-- DROP TABLE public.communications;

CREATE TABLE public.communications (
	comm_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	topic varchar(200) NOT NULL,
	message text NOT NULL,
	communicated_by varchar NULL,
	status varchar NULL,
	communicated_on timestamp NULL,
	created_on timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT communications_pk PRIMARY KEY (comm_id)
);

-- public.bootcamp definition

-- Drop table

-- DROP TABLE public.bootcamp;

CREATE TABLE public.bootcamp (
	activity_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	activity_name varchar(200) NOT NULL,
	description text NOT NULL,
	created_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	event_date date NOT NULL,
	application_link varchar NULL,
	activity_type varchar NULL,
	status varchar NOT NULL,
	CONSTRAINT bootcamp_activities_pk PRIMARY KEY (activity_id)
);
-- public.cisco definition

-- Drop table

-- DROP TABLE public.cisco;

CREATE TABLE public.cisco (
	activity_type varchar NULL,
	status varchar NOT NULL,
	activity_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	activity_name varchar(200) NOT NULL,
	description text NOT NULL,
	created_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	event_date date NOT NULL,
	application_link varchar NULL,
	CONSTRAINT cisco_academy_pk PRIMARY KEY (activity_id)
);

-- public.microsoft definition

-- Drop table

-- DROP TABLE public.microsoft;

CREATE TABLE public.microsoft (
	activity_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	activity_name varchar(200) NOT NULL,
	description text NOT NULL,
	created_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	event_date date NOT NULL,
	application_link varchar NULL,
	activity_type varchar NULL,
	status varchar NOT NULL,
	CONSTRAINT microsoft_activities_pk PRIMARY KEY (activity_id)
);
